version: '3.8'

services:
  app:
    image: vikram143256/javaauto:version1
    ports:
      - "8080:8080"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: overlay
